### ISSUE TITLE
EPIC: PRDT: Explore Accounts

### ISSUE THREAD

**Issue by Dianadec** [bcgov/reserve-rec-api#36]
#### Description:

This ticket is to explore accounts 

#### Acceptance Criteria:

- [ ] Research and recommendation on what log in technology to use 
   - [ ] ~~Ability to log in with social log in~~
   - [ ] Log in with BC Services Card
   - [ ] Log in with universal BCeID
   - [x] Log in/create account from email address
   - [x] Log in with Azure IDIR

#### Development Checklist:

- [x] Cognito configured for OIDC => Azure IDIR
- [x] Azure application setup in dev/test/prod (https://entra.microsoft.com/#home)

#### Dependencies

- Blocked by bcgov/reserve-rec-api#6 
- Related tickets:
-  https://github.com/bcgov/reserve-rec-api/issues/33 and https://github.com/bcgov/reserve-rec-api/issues/32 and https://github.com/bcgov/reserve-rec-api/issues/34

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by LindsayMacfarlane** [comment]
Closing this EPIC. Will create a new EPIC for BCeID if needed.
